### ISSUE TITLE
with-steam-binary build option is ignored

### ISSUE THREAD

**Issue by QkiZMR** [solus-project/linux-steam-integration#13]
I build LSI on Ubuntu 17.04 but option -Dwith-steam-binary=/usr/games/steam is completely ignored. Even if I change default values in meson_options.txt file. I need to create symbolic link to /usr/bin/steam to force lsi-steam work.

**Comment by ikeydoherty** [comment]
What shim mode are you using?

**Comment by ikeydoherty** [comment]
^ There ya go

**Comment by QkiZMR** [comment]
co-exist

**Comment by ikeydoherty** [comment]
The patch is @ https://github.com/solus-project/linux-steam-integration/commit/4b718a4bc77aaf4dc3e90a89be4f6bf385b8d1f0

**Comment by QkiZMR** [comment]
OK, thx. Now works.
