### ISSUE TITLE
Validate Ubuntu support

### ISSUE THREAD

**Issue by ikeydoherty** [solus-project/linux-steam-integration#14]
Seems folks are having issues with LSI on Ubuntu - let's make sure it works there too.

**Comment by JoshStrobl** [comment]
Is there a specific version of Ubuntu this needs to be tested on? I can install it on my laptop and sort it out there.

**Comment by ikeydoherty** [comment]
17.04 and 17.10 I would say. Though I'm wondering with the transition from distro tool to complete runtime if this is needed anymore

**Comment by ikeydoherty** [comment]
Closing as this is gonna be a snap
