### ISSUE TITLE
Steam tray icon missing

### ISSUE THREAD

**Issue by rhssk** [solus-project/linux-steam-integration#2]
After installing LSI, Steam launches, native runtime is successfully disabled, but the Steam tray icon is missing.

Running on:
*Arch 4.5.5-1-ck x86_64 GNU/Linux
*steam 1.0.0.52-2

Launching Steam from terminal doesn't produce much, besides 
[0528/211044:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
which I suppose is irrelevant.

**Comment by ikeydoherty** [comment]
Do you have libappindicator installed? 32-bit version of it

**Comment by rhssk** [comment]
I did not. After installing the package everything works fine and dandy. Thanks!

**Comment by ikeydoherty** [comment]
Awesome! Please let me know how things go, I believe you're the first Arch adopter!

Also, I'm thinking aloud here, but...

What do you think about having some kind of startup check to determine missing libraries when using the native runtime? In future we can expand this to enable distro-hooks, and when we replace the run script it'll be super important

**Comment by rhssk** [comment]
So far things look great. First time I have ever seen my Steam tray menu use system's theme. What a time to be alive.

I mean, it would be great but unfortunately that's all I can say, not that familiar with the more technical aspects. But if you need an Arch user to test things out, I will be more than happy to help, really appreciate the direction you guys are going with Solus and tools like LSI.

**Comment by ikeydoherty** [comment]
Well I appreciate the feedback, and I'm super glad someone has found it useful outside of Solus already :D

I'll be sure to put "help-wanted" labels on issues in future and shoutouts on the internet when we need something tested =)

**Comment by benwaffle** [comment]
from the arch wiki:

However, if you are missing any libraries Steam makes use of, this will fail to launch properly. An easy way to find the missing libraries is to run the following commands:
```
$ cd ~/.local/share/Steam/ubuntu12_32
$ LD_LIBRARY_PATH=".:${LD_LIBRARY_PATH}" ldd $(file *|sed '/ELF/!d;s/:.*//g')|grep 'not found'|sort|uniq
```

**Comment by ikeydoherty** [comment]
@benwaffle yeah when I replace the existing `steam` shell script, i.e. the old `/usr/bin/steam` - I'll need to add startup link checks I think.
