### ISSUE TITLE
Slow mouse movements not registered in CS:GO

### ISSUE THREAD

**Issue by martinfischer** [solus-project/linux-steam-integration#20]
I'm not sure if this is a linux-steam-integration bug, it's been happening since the update yesterday. Maybe libinput? Please delete if this is wrong here.

Mouse movement on the Desktop and even in the in-game menu of CS:GO is ok, but as soon as I am connected to a server and I move the mouse slowly the crosshair won't move.

The sensitivity feels a lot lower all together now as well because of this.

System information:
CPU: Ryzen 5 1600
GPU: Nvidia Geforce GTX 770
Mouse: Steelseries Rival 300

**Comment by martinfischer** [comment]
Tested again after someone else posted the referenced issue above and it is indeed only slow movements down or to the right that are affected. Moving left or up works as normal.

Resolution makes no difference. Tried native 1920x1080 and 4:4 streched. Both have the same problem.

**Comment by martinfischer** [comment]
Last Solus update solved this problem for me. Closing

**Comment by ikeydoherty** [comment]
Yeah sorry for not commenting on here - but I pushed an update for it - the xinput2 enabling in SDL2: https://dev.solus-project.com/R2866:e1f2db10a934e0af9145062ba19ce4f5b946dbf1

Meant to let you know that it was incoming, but I failed to brain
