### ISSUE TITLE
liblsi-intercept crashes Steam streaming

### ISSUE THREAD

**Issue by magicmyth** [solus-project/linux-steam-integration#25]
Running Solus (up-to-date) Budgie install version and trying to stream a game from it to any client - tested both Steam Link and Steam Linux on other machines - causes the the host Steam to crash and restart. If I disable liblsi-intercept via the Linux Steam Integration tool then streaming works just fine.

To rule out it being a window manager issue I installed Kwin and Plasma and tried from there with compositing disabled but Steam still crashed the same way.

Steps to reproduce:
* Enable liblsi-intercept.
* Launch Steam on Solus.
* Launch Steam (same Steam account) on any other client machine (or use a Steam Link).
* On the client machine choose a game to stream from the Solus host and click Stream.
* Steam crashes on Solus host.

I've attached the output of Steam to the console when causing the streaming crash:

[Steam Interceptor Steam Link crash2.txt](https://github.com/solus-project/linux-steam-integration/files/1440879/Steam.Interceptor.Steam.Link.crash2.txt)

I can upload the dmp generated as well if that would help?

My machine is a new Ryzen 5 1600, B350, Radeon R7 370 build with a fresh install of Solus.

**Comment by ikeydoherty** [comment]
> Couldn't load libx264.so.142, x264 support disabled

**Comment by ikeydoherty** [comment]
We might need to do some basic x264 redirection

Please run Steam with `LSI_DEBUG=1` so i can figure out who is tryna load it

**Comment by magicmyth** [comment]
Attached the output with LSI_DEBUG=1 enabled.

[Steam LSI Stream crash-debug.txt](https://github.com/solus-project/linux-steam-integration/files/1443053/Steam.LSI.Stream.crash-debug.txt)

**Comment by ikeydoherty** [comment]
```
>>> Switching video stream from NONE to Desktop_MovieStream
[lsi:steam] blacklisted loading of vendor library: /home/magicmyth/.local/share/Steam/ubuntu12_32/libx264.so.142
Couldn't load libx264.so.142, x264 support disabled
```

**Comment by ikeydoherty** [comment]
@magicmyth try:

```
sudo eopkg it --ignore-dependency https://packages.solus-project.com/unstable/l/linux-steam-integration/linux-steam-integration-0.5-18-1-x86_64.eopkg
```

Restart Steam, and let's see if its working now

**Comment by magicmyth** [comment]
Brilliant thanks. That update solves the issue. I've only tested for 10 minutes but I tried 3 different games and all loaded, streamed and responded just the same as with  LSI disabled.

**Comment by ikeydoherty** [comment]
Awesome, I'll mark this resolved then, thank you :)
