### ISSUE TITLE
Latest steam beta fails to load steamui.so

### ISSUE THREAD

**Issue by martinfischer** [solus-project/linux-steam-integration#29]
After installing the latest steam beta I got the following error:

    You are missing the following 32-bit libraries, and Steam may not run:
    libva.so.1
    libva.so.1
    libva-x11.so.1

And then:

    Fatal Error: Failed to load steamui.so

Steam won't load.

I googled and found a temporary fix here: https://github.com/NixOS/nixpkgs/issues/31384

    $ rm -r ~/.local/share/Steam/ubuntu* ~/.local/share/Steam/package/beta

After this I was able to install steam again and re-login. I did get another warning about libc, but steam works anyways. I opted out of the beta for now.

I also found a bug report on the ValveSoftware/steam-for-linux repository from the NixOS guy, where Valve says the won't fix this issue, it's a maintainer problem: https://github.com/ValveSoftware/steam-for-linux/issues/5233

**Comment by Dynamic-Gravity** [comment]
Same, I am on the Steam Beta channel and when I updated this morning I have this exact same error.

**Comment by ikeydoherty** [comment]
Guys help me out here. What **DISTRO** are you on? There is nothing that LSI can do, as LSI is about using **native** libraries. You need the 32-bit version of libva installed, on Solus this is `libva-32bit`.

Valve is right that this is a maintainer issue, note that we adapted our package in Solus: https://dev.solus-project.com/R2962:25ae74046546a8d544ab67df5f68fcd83a0a1b32

**Comment by martinfischer** [comment]
Solus 3 install, latest updates.

It works with the stable steam channel (for now), but if you opt in to the steam beta within the steam client these errors will come up since today.

**Comment by Dynamic-Gravity** [comment]
@ikeydoherty 
```
sudo eopkg it -y libva-32bit libva-32bit-devel libvdpau-32bit libvdpau-32bit-devel
```
resolves the problem.

**Comment by ikeydoherty** [comment]
No no no. Install `libva-32bit`.  I've already fixed this in unstable. I only run unstable. You do **not** need devel packages.

**Comment by Dynamic-Gravity** [comment]
Alright I'll remove the devel. Not sure if I'd need them or not.

**Comment by ikeydoherty** [comment]
I told you what to install already....

**Comment by martinfischer** [comment]
Alright, installing libva-32bit resolves the issue for me. Updated to beta again, no problems.

**Comment by Dynamic-Gravity** [comment]
After installing the libva it complained about libpau so I needed to install that as well.

**Comment by ikeydoherty** [comment]
@Dynamic-Gravity on NV hardware or just in general? Because I can add the rundeps to either the nvidia or steam pkg

**Comment by Dynamic-Gravity** [comment]
@ikeydoherty  I don't use Nvidia, I use AMD.
```
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Fiji [Radeon R9 FURY / NANO Series] (rev cb)
```

**Comment by ikeydoherty** [comment]
Huh ok, well I'll add that dep onto it

**Comment by martinfischer** [comment]
I am on Nvidia. libvdpau-32bit was already installed for me.

**Comment by ikeydoherty** [comment]
@martinfischer yeah that explains the difference between the systems then. I'll add it onto steam pkg just for safety

**Comment by Dynamic-Gravity** [comment]
@ikeydoherty thanks for the assistance. :)

**Comment by ikeydoherty** [comment]
Nah thank you guys for figuring out the last mile. At least we have less panic here than the other thread, eh? :P

Fix in Solus unstable: https://dev.solus-project.com/R2962:9a6d45ab0264d6c96786fe976897c8632d7e8539

I have a suspicion I'm gonna need to manually move steam, linux-steam-integration, libressl-shim packages into stable as sync isn't til Friday and a number of people are hitting this now..

**Comment by martinfischer** [comment]
I mean it's affecting people who run steam beta, our own fault :P

**Comment by Dynamic-Gravity** [comment]
Yeah, I'm not on unstable but I run with Steam beta. A lot of normies I wouldn't have had this fixed until the Friday sync.

**Comment by ikeydoherty** [comment]
Yeah but we get new shiny :3 And precompiled Vulkan shaders... xD

**Comment by Dynamic-Gravity** [comment]
> Yeah but we get new shiny :3 And precompiled Vulkan shaders... xD

temptation to switch to unstable grows...

**Comment by ikeydoherty** [comment]
We're going to conduct a cherry-pick sync into stable today

**Comment by ikeydoherty** [comment]
Done
