### ISSUE TITLE
Skullgirls: can't locate libSDL2_locale.so.0

### ISSUE THREAD

**Issue by stryan** [solus-project/linux-steam-integration#31]
Running a fresh install of Solus, the game Skullgirls is unable to run due to not being able to find a library:

/home/*****/.local/share/Steam/steamapps/common/Skullgirls/SkullGirls.x86_64-pc-linux-gnu: error while loading shared libraries: libSDL2_locale.so.0: cannot open shared object file: No such file or directory

The library appears to have been packaged with the game itself (as there's a copy of that file in ~/.local/share/Steam/steamapps/common/Skullgirls/lib). With LSI native runtime turned off the game functions correctly.

Is there a way to have Steam/LSI prioritize packaged-with-game libraries over searching on the system? I'm unable to find a package that would provide libSDL2_locale.so.0 on either the Solus distros or in general. I'd rather avoid symlinking the libraries to my path if possible.

**Comment by ikeydoherty** [comment]
We can fix the issue. I can let it pass through or find out what its actually meant to be..

**Comment by ikeydoherty** [comment]
After my changes:

![screenshot from 2017-11-10 02-25-42](https://user-images.githubusercontent.com/164489/32640039-919cbdd8-c5be-11e7-8953-a84d7bb978c0.png)

This will be in tomorrows sync, sorry about that. Didn't expect anyone to go abusing the libSDL name like that
