### ISSUE TITLE
libbz2 is missing / can't load steamui

### ISSUE THREAD

**Issue by DarthWound** [solus-project/linux-steam-integration#38]
Hello, wanted to try LSI after watching this project since a long time.

Used Copr repo for Fedora, followed all instructions, and I have bz2 libs installed (32&64 bits).
However when I launch LSI Steam, it says that libbz2 is missing and that it can't load steamui.

I have Steam from RPMFusion, installed and used before trying LSI.
Client switched to beta version. Didn't try Negativo17 version but shouldn't be required.

**Comment by DarthWound** [comment]
Thank you for this fast answer Ikey!

Ok you made me realize that instructions found on Copr page were missing something.
In /usr/lib/ I have libbz2.so.1.0.6 and libbz2.so.1 but not libbz2.so.1.0.

After doing `su -c 'ln -sf /usr/lib/libbz2.so.1.0.6 /usr/lib/libbz2.so.1.0'` LSI Steam runs well. It should be added in Copr instructions, however command for libudev 32-bit was given.

Sorry for wasting your time :laughing: and keep up the good work!
Feel free to contact me if you have any problem in Steam community, I'm a global moderator :)

**Comment by ikeydoherty** [comment]
No no not a waste of time at all! Here lemme add a fix into LSI for you

**Comment by ikeydoherty** [comment]
Should do the trick nicely: 287781356c705fabafdc3c358393d7e67dd99e54

**Comment by ikeydoherty** [comment]
Ah .1.0 - lemme refix :P

**Comment by ikeydoherty** [comment]
There. xD

**Comment by DarthWound** [comment]
Thanks. So linking `libbz2` shouldn't be necessary now, LSI taking care of it directly, right?

By the way, following instructions in the Copr page, this is what we have to do for Fedora26/27:
`/usr/lib64/libbz2.so.1.0.6` -> `/usr/lib64/libbz2.so.1.0`
`/usr/lib/libbz2.so.1.0.6` -> `/usr/lib/libbz2.so.1.0` _(that's the one we found here)_
`/usr/lib64/libudev.so.1.6.6` -> `/usr/lib64/libudev.so.0`
`/usr/lib/libudev.so.1.6.6` -> `/usr/lib/libudev.so.0`

**Comment by ikeydoherty** [comment]
Yeah the next release of LSI will automatically redirect to the correct bz2. What's the story with udev, and do you have a `libudev.so.1` ?

**Comment by DarthWound** [comment]
Don't know, it's just from the instructions in [Copr repo](https://copr.fedorainfracloud.org/coprs/alunux/linux-steam-integration/) but I can't tell if it's really needed or not regarding udev.

And yes, I have `libudev.so.1` in both 32bits/64bits directories _(as links)_. And it's probably default because if I remember well I only linked libs in user directories when I was tweaking my Steam installation a few months ago, not in root directories including `/usr/lib` and `/usr/lib64`.

**Comment by ikeydoherty** [comment]
Yeah - fwiw I know that some stuff can require `libudev.so.0` - just can't remember what. If it becomes a problem, well, we'll stick a new rule in.

**Comment by DarthWound** [comment]
Thank you again!

**Comment by ikeydoherty** [comment]
Np bud :) FWIW my hope is we can eventually wean folks off the distro packages and move towards the snap and solve all of these kinds of issues, and ensure the runtime is open for solid contributions (as well as the Solus base). But I suspect when that guy goes out public, we're gonna need an army of willing testers.. :)

**Comment by DarthWound** [comment]
I heard of the snap version, I'll try it if I have some spare time. Like many others, I would prefer Flatpak instead of Snap :p but we really can't complain, what you did for Steam integration is awesome _(and I speak as someone who's close to Valve)_ and bringing everything to other people instead of keeping that for Solus as a killer feature is great.

**Comment by ikeydoherty** [comment]
It'll be a short while before I consider the snap ready for prime time fwiw. Though I'd argue one of the killer features of Solus is that we care about portability and architecture a *lot* :)

**Comment by alunux** [comment]
@DarthWound thanks for bringing this issue to upstream. Finally, this issue was fixed, thanks @ikeydoherty!

**Comment by ikeydoherty** [comment]
> Finally, this issue was fixed

Can't fix what I don't know about. :)

**Comment by DarthWound** [comment]
@alunux Are the instructions (about symlinks) mandatory? It seems that these steps aren't required if they are handled by LSI but I could be wrong. BTW in your readme you're talking about Steam from negativo17 but package from RPMFusion works flawlessly too. Thank you for updating the package.

**Comment by alunux** [comment]
@DarthWound No, we don't need to do that again. After I update the repo, I will update the readme too :)

**Comment by DarthWound** [comment]
Nice. By the way did you think about making your packages available in RPMFusion?

Coprs are often testbeds before getting in official repositories or RPMFusion. This way we avoid using several thirdparty repos that may break, like what happens with PPAs on Ubuntu.

**Comment by ikeydoherty** [comment]
Do note however that LSI can only do these tricks when `liblsi-intercept` is enabled, which infers using native runtime

**Comment by DarthWound** [comment]
Thank you for giving this detail. Not a problem for me as I enable everything except force 32-bits mode.

**Comment by ikeydoherty** [comment]
Sweet! As LSI has evolved this has become the preferred mode, and tbh this is where LSI actually *kicks in*. In time we'll sorta frown on not using those options as it would lead to unexpected experiences (like, idk, not working)

**Comment by DarthWound** [comment]
Well, I enabled them because imo it doesn't make sense to install LSI if it's to disable two options that actually make LSI awesome and useful :D

**Comment by alunux** [comment]
Can libudev be handled by LSI too? Without it, Steam gets stuck at "Connecting Steam account: user...". On Fedora 26/27, we have:

**Comment by alunux** [comment]
It was fixed by doing symlink:
```sh
ln -sf /usr/lib64/libudev.so.1.6.6 /usr/lib64/libudev.so.0
ln -sf /usr/lib/libudev.so.1.6.6 /usr/lib/libudev.so.0
```

**Comment by ikeydoherty** [comment]
Can you try it with https://github.com/solus-project/linux-steam-integration/commit/f8b583bc0b9fbed0b0e5131504eae4d277674553 applied and see if that resolves the issue?

**Comment by alunux** [comment]
@ikeydoherty OMG, it works!
`[lsi:steam] transforming vendor soname: libudev.so.0 -> libudev.so.1`
![screenshot from 2017-11-15 21 47 47](https://user-images.githubusercontent.com/10938708/32842085-c097d0ca-ca4e-11e7-947a-4071b703ab90.png)

**Comment by ikeydoherty** [comment]
#magic :D

**Comment by DarthWound** [comment]
Was wondering why my DNF update told me `cannot install the best update candidate for package linux-steam-integration-libs-0.6-2.fc27.i686 - nothing provides linux-steam-integration = 0.6-3.fc27 needed by linux-steam-integration-libs-0.6-3.fc27.i686`, now I know :D a new build with this patch is pending in Copr.

**Comment by alunux** [comment]
@DarthWound Aha, sorry, Copr build is not finished yet :(
https://copr.fedorainfracloud.org/coprs/alunux/linux-steam-integration/build/662304/

**Comment by DarthWound** [comment]
Build failed for F26-32, F26-64, and F27-64.

**Comment by alunux** [comment]
@DarthWound try again :)

**Comment by DarthWound** [comment]
It's ok now :)

Poor Ikey, Fedora users spamming his notifications :angel:

**Comment by ikeydoherty** [comment]
lol
