### ISSUE TITLE
Mount snap "solus-runtime-gaming" (11) (info failed to parse: invalid snap type: "base")

### ISSUE THREAD

**Issue by Leeo97one** [solus-project/linux-steam-integration#48]
So I tried to install LSI via snap but:
```
 leeo  ~  sudo snap install --edge solus-runtime-gaming
2017-12-30T12:59:21+01:00 INFO Waiting for restart...
error: cannot perform the following tasks:
- Mount snap "solus-runtime-gaming" (11) (info failed to parse: invalid snap type: "base")
 leeo  ~  sudo snap install --devmode --edge solus-runtime-gaming
[sudo] Mot de passe de leeo : 
2017-12-30T13:22:22+01:00 INFO Waiting for restart...
error: cannot perform the following tasks:
- Mount snap "solus-runtime-gaming" (11) (info failed to parse: invalid snap type: "base")
```
I tried on Arch Linux and Debian (Buster).

**Comment by ikeydoherty** [comment]
What version of snapd do you have? Because it sounds a lot like its too old

**Comment by Leeo97one** [comment]
Arch Linux: https://www.archlinux.org/packages/community/x86_64/snapd/ (2.26.1)
Debian: https://packages.debian.org/buster/snapd (2.27.6)

**Comment by ikeydoherty** [comment]
Far too old, you need at least 2.29.4 + patches or 2.30 stable :/

**Comment by Leeo97one** [comment]
Oh OK x)
Do you plan tu use Flatpak? Because snap is supported correctly only by very few distribs as far I know...

**Comment by ikeydoherty** [comment]
I have no such plans at this time, sorry.
