### ISSUE TITLE
is LSI intended to be integrated by devs or users

### ISSUE THREAD

**Issue by philipzae** [solus-project/linux-steam-integration#5]
i was curious to know whether the intent of LSI is for distro developers to integrate it into the distro, or is it intended for regular users to install it.

**Comment by ikeydoherty** [comment]
Ideally distro developers, but if we can come up with a nice way to install it for users then we should

**Comment by philipzae** [comment]
heard you talk about how good the steam runtime in solus was on a podcast and wanted to get it running on ubuntu mate and linux mint. :D

**Comment by ikeydoherty** [comment]
Closing this because I don't think there's an actual issue here =)
