### ISSUE TITLE
Wrong snap package name in readme

### ISSUE THREAD

**Issue by J4nsen** [solus-project/linux-steam-integration#50]
Hi, 
the current readme states to install the (snap) runtime and lsi with

> sudo snap install --edge solus-runtime-gaming
> sudo snap install --devmode --edge solus-runtime-gaming

but it should be

> sudo snap install --edge solus-runtime-gaming
> sudo snap install --devmode --edge linux-steam-integration

**Comment by ikeydoherty** [comment]
Fixed, sorry bout that
