### ISSUE TITLE
Cannot browse to /opt/ to add library

### ISSUE THREAD

**Issue by RlndVt** [solus-project/linux-steam-integration#52]
Games that I want installed on my SSD I want to put in /opt/games/SteamLibrary, but I cannot browse to /opt/ when selecting a new library.

Ubuntu 16.04, LSI 0.7.2.

**Comment by RlndVt** [comment]
Added image for proof that /opt/ (and other directories for that matter) are missing, and a non existing 'meta' directory is listed.

![screenshot](https://user-images.githubusercontent.com/1658570/35129283-34709ea2-fcbb-11e7-8136-bdf7f2f07323.png)

**Comment by ikeydoherty** [comment]
The confinement will not allow access to `/opt` - only `~` (no dotfiles)` and `/media` / `/run/media` mounts.

**Comment by RlndVt** [comment]
If you add a symlink in ~ to a folder in /opt/, would that give access or
would the confinement also restrict that?

**Comment by ikeydoherty** [comment]
It'd still forbid that yeah

**Comment by RlndVt** [comment]
Ok thanks.

Too much of a limitation for me personally.
