### ISSUE TITLE
LSI opens different icon

### ISSUE THREAD

**Issue by AccountOneOff** [solus-project/linux-steam-integration#53]
I added LSI to my favorites and instead of opening on the existing icon it opens on a new one.

- Ubuntu 17.10
- Gnome 3.26.2
- Dash to Panel extension

Made LSI icon black to distinguish the two:

![](https://i.imgur.com/rh89Rm5.png)

**Comment by davidpocina** [comment]
Adding this to the desktop file should fix the issue:
StartupWMClass=Steam

I will open a pull request with this when I have a minute
