### ISSUE TITLE
Make Solus Steam Integration installation easier on Ubuntu

### ISSUE THREAD

**Issue by AsciiWolf** [solus-project/linux-steam-integration#54]
Solus Steam Integration can be currently installed on Ubuntu only by using the command line snap command. Please, consider making the Solus Steam Integration snap installable out-of-box using Ubuntu Software on Ubuntu.

**Comment by ikeydoherty** [comment]
I assume by Ubuntu Software you mean GNOME Software.

The LSI Snap is currently unstable and is still requiring further snapd work, which we're waiting on jdstrand coming back to work so we can define the new interface. Until that point, we will not have
a stable snap.

One the snapd work is done, we'll be able to get the snaps stable, at which point they'll show up
in any snap supporting software center.

**Comment by AsciiWolf** [comment]
Any news?

**Comment by AsciiWolf** [comment]
Any news?
