### ISSUE TITLE
Steam isn't currently installed at /usr/lib/steam/steam

### ISSUE THREAD

**Issue by sunofsparda** [solus-project/linux-steam-integration#55]
Hello,
I am facing this "Steam isn't currently installed at /usr/lib/steam/steam" when trying to launch LSI
OS: Manjaro
`-> % which steam`
`/usr/bin/steam`

**Comment by sunofsparda** [comment]
FIXED:
`ln -s /usr/bin/steam /usr/lib/steam/steam`
Or edit PKGBUILD from: `-Dwith-steam-binary=/usr/lib/steam/steam` to `-Dwith-steam-binary=/usr/bin/steam`

**Comment by ikeydoherty** [comment]
Preferable to just configure LSI correctly :) See the docs and make sure you configure LSI in the right mode (shim or replacement) and the appropriate "real steam" path
