### ISSUE TITLE
Readme doesn't actually explain what improvements are offered by this package

### ISSUE THREAD

**Issue by djmattyg007** [solus-project/linux-steam-integration#6]
I have no idea if I should actually install this because I can't easily tell exactly what it does over not using it.

**Comment by ikeydoherty** [comment]
It forces Steam to work properly. It allows you to turn off the Steam runtime and use your own OS runtime without issue, which leads to less bugs and enhanced performance (no ancient libs..)

It also forces the Steam client to fit in, so no ugly font issues from using the wrong fontconfig, no unthemed tray icon from using its own GTK, etc.

Lastly, it lets you still use Steam's runtime on modern distros, where Steam no longer starts without coercing or butchering the runtime (most distros now have some hook to do this - even openSUSE).
It will "just work" when you start it up, whichever route you wish to take, without irreversibly butchering your own local Steam install.

**Comment by djmattyg007** [comment]
You should put that in the Readme file :)

**Comment by ikeydoherty** [comment]
Indeedy. It's .rst so I need to convert to .md because sod that

**Comment by ikeydoherty** [comment]
Done :)
