### ISSUE TITLE
Steam beta update

### ISSUE THREAD

**Issue by Feanor1397** [solus-project/linux-steam-integration#7]
In latest steam beta update was introduced new runtime behaivor and steam now trying load system libraries by default. Also two new variables are there
* Improved interactions between the Steam runtime and host distribution libraries, which should let Steam work out of the box with open-source graphics drivers on modern distributions. If using an older distribution or running into problems, use STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 to revert to previous behavior.
* Unify close-to-tray behavior with other platforms. If using a distribution that doesn't have proper compatible tray support, use STEAM_FRAME_FORCE_CLOSE=0 

So, can you make switches for this new functions? This would be very convenient

**Comment by ikeydoherty** [comment]
Yeah we should probably revamp the GTK UI too - thoughts? Feel free to ping anyone too btw

**Comment by Dynamic-Gravity** [comment]
@ikeydoherty Any updates on use with LSI with Steam Beta from the official repo?

**Comment by ikeydoherty** [comment]
No longer relevant - we control dynamic linking ourselves in 0.4
