### ISSUE TITLE
Steam Update breaks LSI on Arch Linux.

### ISSUE THREAD

**Issue by Astilex5** [solus-project/linux-steam-integration#74]
Hello,

Today Valve pushed an update that broke LSI on Arch Linux.

I got the `Failed to load steamui.so` error. Both normal Runtime and Native Runtime provided by Arch work fine.

Here is the output:
`Failed to load steamui.so - dlerror(): /home/$USER/.local/share/Steam/ubuntu12_32/steamui.so: undefined symbol: SDL_GameControllerMappingForDeviceIndex
`
I am not sure what to do here since Runtime and N-Runtime are working fine. I found Non-LSI solutions but I would like to avoid mixing and matching libs/commands
.
Any ideas on how to fix this?

**Comment by thoughton** [comment]
I've hit the same problem on Ubuntu 16.04 after Steam updated when I tried to load it today.
I get the exact same error about `SDL_GameControllerMappingForDeviceIndex`.

**Comment by fcuzzocrea** [comment]
I had the very same problem on openSuse Leap 15.0 running lsi-steam. With the previous update was working correctly.
The issue shows up only by using LSI steam, if I run STEAM_RUNTIME=0 steam, the client launch and works

**Comment by thoughton** [comment]
I don't know what the relevance is, but I've just noticed that turning `Off` the `Use the Intercept library` setting in the "Linux Steam Integration" settings app allows the Steam client to launch correctly.
Does this help anyone narrow down what the issue is?

**Comment by ghost** [comment]
@thoughton Thanks it helped me :)

**Comment by bmwalters** [comment]
Steam cherry-picked some SDL updates from unreleased 2.0.9. Arch is shipping 2.0.8 which is current stable. Turning on the intercept library loads Arch's SDL instead of the one Steam ships. Issue should be resolved when SDL 2.0.9 is officially released.

**Comment by ghost** [comment]
When is it going to be released?

**Comment by ghost** [comment]
2.0.9 is released! Everything works again

**Comment by alunux** [comment]
Everything works again too on Fedora.

**Comment by SakiiCode** [comment]
I use manjaro with sdl2 2.0.9-1 and still gives this error

```
Running Steam on manjarolinux 18.0.4 64-bit
STEAM_RUNTIME is disabled by the user
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
Failed to load steamui.so - dlerror(): /home/*********/snap/linux-steam-integration/common/.local/share/Steam/ubuntu12_32/steamui.so: undefined symbol: SDL_GameControllerMappingForDeviceIndex
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
[2019-06-30 23:20:36] Startup - updater built Jun 17 2019 23:31:08
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2019-06-30 23:20:36] Checking for update on startup
[2019-06-30 23:20:36] Checking for available updates...
[2019-06-30 23:20:36] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
[2019-06-30 23:20:36] Download skipped: /client/steam_client_ubuntu12 version 1560817063, installed version 1560817063
[2019-06-30 23:20:36] Nothing to do
[2019-06-30 23:20:36] Verifying installation...
[2019-06-30 23:20:36] Performing checksum verification of executable files
[2019-06-30 23:20:37] Verification complete
[2019-06-30 23:21:46] Shutdown

```

**Comment by lucasfcnunes** [comment]
> I don't know what the relevance is, but I've just noticed that turning `Off` the `Use the Intercept library` setting in the "Linux Steam Integration" settings app allows the Steam client to launch correctly.
> Does this help anyone narrow down what the issue is?

@thoughton worked!
Is this `Use the Intercept library` important?

**Comment by Newk77** [comment]
seems like this bug came back again after last night's update.. changing settings like pointed out here didn't seem to bring back the UI yet
