### ISSUE TITLE
SteamPlay Esync

### ISSUE THREAD

**Issue by Mark12870** [solus-project/linux-steam-integration#76]
Hello,
I had a problem with GTA5 over SteamPlay. I use Solus distro and I've got Geforce GTX960.

1) To be able to start this game, I had to disable Esync first. And it worked but with terrible performance.
2) Then I found out that the Esync must be enabled to get better performance, but it doesn't work out of the box. So I found on internet this solution: https://forum.manjaro.org/t/increase-fd-limits-to-let-steam-play-works-reliably/56270/6 and now it works well now. According to that solution its needed to increase DefaultLimitNOFILE.

I think the esync is needed also for other games and the low DefaultLimitNOFILE is preventing it from working correctly.

Could you please somehow integrate automatic change of this DefaultLimitNOFILE to Solus or Linux Steam Integration?

Thank you.

**Comment by ThisNekoGuy** [comment]
It seems your forum link is either missing or private now.

Thought I would say something considering that SteamPlay/Proton is a big deal for Linux Gaming now and there's another issue regarding Proton having issues here.
I'd love to have some of my native games, like, not crash all the time but trading that for Proton is not easy and having to switch between Bundled and Native in ISL just for Proton is a pain.

**Comment by Mark12870** [comment]
Well, this is 2 years old issue and I even think they fixed it in Solus.

**Comment by ThisNekoGuy** [comment]
I'm just a concerned Manjaro user (usung LSI), but sure
