### ISSUE TITLE
Missing libbz2.so.1.0.6

### ISSUE THREAD

**Issue by ranisalt** [solus-project/linux-steam-integration#82]
I have the following error log:

```
/home/rsa/.local/share/Steam/steam.sh: line 114: VERSION_ID: unbound variable
/home/rsa/.local/share/Steam/steam.sh: line 114: VERSION_ID: unbound variable
Running Steam on arch  64-bit
STEAM_RUNTIME is disabled by the user
Error: You are missing the following 32-bit libraries, and Steam may not run:
libbz2.so.1.0.6
libbz2.so.1.0.6
Error:
You are missing the following 32-bit libraries, and Steam may not run:
libbz2.so.1.0.6
libbz2.so.1.0.6
Press enter to continue: Installing breakpad exception handler for appid(steam)/version(1563411792)
Installing breakpad exception handler for appid(steam)/version(1563411792)
Installing breakpad exception handler for appid(steam)/version(1563411792)
Failed to load steamui.so - dlerror(): libbz2.so.1.0.6: cannot open shared object file: No such file or directory
Installing breakpad exception handler for appid(steam)/version(1563411792)
Installing breakpad exception handler for appid(steam)/version(1563411792)
[2019-07-28 06:18:58] Startup - updater built Jul 18 2019 00:11:24
[2019-07-28 06:18:58] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2019-07-28 06:18:58] Checking for update on startup
[2019-07-28 06:18:58] Checking for available updates...
[2019-07-28 06:18:58] Downloading manifest: client-download.steampowered.com/client/steam_client_publicbeta_ubuntu12
[2019-07-28 06:18:59] Download skipped by HTTP 304 Not Modified
[2019-07-28 06:18:59] Nothing to do
[2019-07-28 06:18:59] Verifying installation...
[2019-07-28 06:18:59] Performing checksum verification of executable files
[2019-07-28 06:19:00] Verification complete
[2019-07-28 06:19:00] Shutdown
```

Enabling steam runtime fixes, but then a shitload of games are broken because of ancient libraries. So I either can't play or can't play here.

I tried building v1.0.6 of libbz2 (Arch uses 1.0.8 already) but steam refuses to find it at `/usr/lib{,32}/libbz2.so.1.0.6`.

**Comment by ranisalt** [comment]
Running `lsi-steam --reset` and then starting up again fixed, I guess my runtime was broken.

**Comment by ranisalt** [comment]
Actually, it did not, it's just that lsi-settings utility was not persisting the config. bz2 1.0.6 is still missing.

The same issue does not happen by running `steam-native` instead.

**Comment by markuschaaf** [comment]
This is caused by commit 287781356c705fabafdc3c358393d7e67dd99e54. After reverting it, lsi-steam starts on my Manjaro box. Of course the SDL problem is still there, which means you can't use the native runtime.

**Comment by ranisalt** [comment]
@ikeydoherty hey can you say something about this? I'm tagging you as you made the commit. It helps Fedora but breaks Arch/Manjaro

Edit: the error in Arch is a different one now, it has bz2 1.0.8 instead of 1.0.6 so it points to the wrong lib.

**Comment by famiu** [comment]
I have the same issue, how can I fix this?

**Comment by ranisalt** [comment]
> I have the same issue, how can I fix this?

Clone and revert 2877813 (`git revert 2877813`), then compile again.

**Comment by ranisalt** [comment]
Is this project abandoned?

**Comment by famiu** [comment]
Seems like it might be, the last commit was on May 20, 2018
